### ISSUE TITLE
Pilot power supply voltages are not shown or shown wrong, improvements recommended

### ISSUE THREAD

**Issue by jerkey** [OpenEVSE/OpenEVSE_PLUS#1]
IC4, the op-amp in the Pilot section, is shown with its negative power supply pin labeled "GND" but it is actually connected to VOUT- from the DCDC converter, whose GND is connected to actual GND of the circuit.  Neither VOUT- nor VOUT+ are labeled with voltages, but I was able to look up the DCDC power supply "D107E" and find out that it produces -12 and +12 volts from a FIVE volt input supply.

However, "DCDC" the D107E is shown in the schematic to be powered with +12v (coming from U$1 the AC-DC power supply) which would fry it if you try it.  Since the part called "TVS" is a 13.6v Zener diode (I had to look this up) there is really no need for a seperate DCDC converter...

I recommend deleting most of the parts inside the "Pilot" box and using instead an IXDD604PI mosfet driver chip, which you power directly from the +12v supply from the AC-DC power supply.

I would update the schematic but I use KiCAD not Eagle so I would have to start over.

Thank you for publishing this design.

**Comment by chris1howell** [comment]
Deleting the DCDC and circuitry is not possible, SAE J1772 requires the pilot signal to operate at +12v HIGH and -12v LOW. The charging station to verify an EV is present, which is performed by a "diode check" at -12v. Several SAE J1772 error stated require the pilot to be pulled to -12v.

The bi-derectional TVS +13.6 and -13.6 is for surge, static and other transient spikes not for voltage regulation.

Part D107E (for 5v input) and D117E (for 12v input) were discontinued several years ago. The current OpenEVSE PLUS v4 uses part MD112D-12 in the Bill of Materials.

The recommended modifications and MOSFET driver would result in a non-compliant SAE J1772 pilot signal. The current design is mature and fully complaint with 100% compatibility on all vehicles tested.
