### ISSUE TITLE
Bill of materials not ok?!

### ISSUE THREAD

**Issue by micdre** [OpenEVSE/OpenEVSE_PLUS#2]
Hello,

I found out that the BOM list, genretated in Eagle, is not ok in version 4 and 3! (maybe other versions too)
Is there somewhere a good list.

Regards, Michel

**Comment by chris1howell** [comment]
I will take a look at the Eagle generated BOM. Any information on what parts are not okay?

**Comment by micdre** [comment]
Hello
Thanks!

IC2 is not a mega 8 but a 328P
IC3 is not a LMV358 but a LM358
IC4 is not a LMV358 bu a LF353
Maybe there's more...

Costs me a couple of parts....

Regards, Michel

Verstuurd vanaf mijn iPhone

Op 11 apr. 2017 om 21:39 heeft Chris Howell <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I will take a look at the Eagle generated BOM. Any information on what parts are not okay?

**Comment by chris1howell** [comment]
I updated the following part values so generic footprints report the correct part when exporting Eagle generated BOM.

IC2 value 328P 
IC3 value LM358 
IC4 value LF353
TVS value P6SMB16CA
D1 value AZ23C5V6-7-F

**Comment by micdre** [comment]
In wich version of the board?

Verstuurd vanaf mijn iPhone

Op 11 apr. 2017 om 22:07 heeft Chris Howell <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I updated the following part values so generic footprints report the correct part when exporting Eagle generated BOM.

IC2 value 328P
IC3 value LM358
IC4 value LF353
TVS value P6SMB16CA
D1 value AZ23C5V6-7-F

**Comment by chris1howell** [comment]
V4.

On Apr 11, 2017 1:26 PM, "micdre" <notifications@github.com<mailto:notifications@github.com>> wrote:
In wich version of the board?

Verstuurd vanaf mijn iPhone

Op 11 apr. 2017 om 22:07 heeft Chris Howell <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com<mailto:notifications@github.com>>> het volgende geschreven:


I updated the following part values so generic footprints report the correct part when exporting Eagle generated BOM.

IC2 value 328P
IC3 value LM358
IC4 value LF353
TVS value P6SMB16CA
D1 value AZ23C5V6-7-F

**Comment by micdre** [comment]
Thanks!

Verstuurd vanaf mijn iPhone

Op 11 apr. 2017 om 22:34 heeft Chris Howell <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

V4.

On Apr 11, 2017 1:26 PM, "micdre" <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:
In wich version of the board?

Verstuurd vanaf mijn iPhone

Op 11 apr. 2017 om 22:07 heeft Chris Howell <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com<mailto:notifications@github.com>>> het volgende geschreven:


I updated the following part values so generic footprints report the correct part when exporting Eagle generated BOM.

IC2 value 328P
IC3 value LM358
IC4 value LF353
TVS value P6SMB16CA
D1 value AZ23C5V6-7-F
