### ISSUE TITLE
Math / Theory of the GFCI circuit

### ISSUE THREAD

**Issue by RyanCopley** [OpenEVSE/OpenEVSE_PLUS#5]
I did find the theory of operations, and I reviewed the burden resistor calculator, but I am at odds with trying to understand how a burden resistor of 412 ohms was selected. 

For the CT being used (http://www.crmagnetics.com/Assets/ProductPDFs/CR8400%20Series.pdf) it has the specs
Max RMS Current / Ir = 20 amps
Current Sensor turn ratio / Te = 1011:1
The arduino System Voltage is 5v

I plug these values in to https://tyler.anairo.com/projects/open-energy-monitor-calculator and I get a burden resistor of 89 ohms. Are you scaling down the max RMS current to ~4.3 amps for more sensitive detections?

Could you also go into explaining what the first OP Amp is for? I understand why the second one exists, but the first is elusive to me. My current guess is that it's being used as memory to keep an unbalanced current to remain a high value even whilst it oscilates

I would really appreciate the help understanding the theory here :-)

**Comment by chris1howell** [comment]
The coil is scaled way down, there is no point reading anything over 20ma.
Sensitivity to low currents is more important.

The first stage of the Opamp is a amplifier or multiplyer. The input which
is a very tiny voltage is amplified before hitting the second stage which
is a voltage comparator. If the amplified voltage from the coil is above
the threshold the output of the opamp goes high. The Inturupt on the
microprocessor is triggered on the rising voltage of the opamp output.

**Comment by RyanCopley** [comment]
Thank for you for the explanation, that is really helpful!
